export const defaultSeedData = {
  admins: [
    {
      id: 'admin-1',
      name: 'NahnuHost Developer',
      email: 'admin@nahnuhost.com',
      passwordHash: 'admin123',
      role: 'admin',
    },
  ],
  clients: [
    {
      id: 'cli-1',
      name: 'Budi Santoso',
      company: 'Toko Berkah Mandiri',
      email: 'budi@tokoberkah.id',
      phone: '6281298765432',
      address: 'Jl. Pahlawan No. 12, Bandung, Jawa Barat',
      joinedDate: '2025-08-15',
      status: 'active',
      segment: 'umkm',
      notes: 'Klien e-commerce fashion & produk herbal, bayar selalu tepat waktu.',
    },
    {
      id: 'cli-2',
      name: 'Siti Rahmah',
      company: 'PT Cahaya Abadi Logistik',
      email: 'siti@cahayaabadilogistik.com',
      phone: '6281355588990',
      address: 'Gedung Wisma Niaga Lt. 4, Surabaya, Jawa Timur',
      joinedDate: '2025-04-10',
      status: 'active',
      segment: 'enterprise',
      notes: 'Klien corporate logistik ekspor-impor, langganan maintenance bulanan.',
    },
    {
      id: 'cli-3',
      name: 'dr. Hendro Wijaya',
      company: 'Klinik Sehat Medika',
      email: 'hendro@sehatmedika.co.id',
      phone: '6285712349988',
      address: 'Jl. Boulevard Raya Blok A2, Gading Serpong, Tangerang',
      joinedDate: '2025-01-20',
      status: 'active',
      segment: 'enterprise',
      notes: 'Website reservasi dokter & profil poliklinik, butuh reminder H-7 dan H-3 WhatsApp.',
    },
    {
      id: 'cli-4',
      name: 'Dewi Lestari',
      company: 'Artha Interior Studio',
      email: 'dewi@arthainterior.com',
      phone: '6281809001122',
      address: 'Jl. Danau Toba No. 8, Denpasar, Bali',
      joinedDate: '2025-11-05',
      status: 'active',
      segment: 'personal',
      notes: 'Studio desain interior arsitek, butuh galeri portfolio visual cepat.',
    },
  ],
  products: [
    {
      id: 'prod-landing',
      name: 'Jasa Pembuatan Landing Page',
      category: 'website',
      description: 'Halaman promosi penjualan single-page berkonversi tinggi, mobile responsive, dan terintegrasi WhatsApp checkout.',
      badge: 'Populer',
      active: true,
      features: [
        'Single Page High Converting',
        'Free Domain .com (1 Tahun)',
        'High Speed Cloud Hosting 1GB',
        'Copywriting Sales & CTA WhatsApp',
        'Integrasi Pixel & Google Analytics',
        'Revisi 2x & Garansi 30 Hari',
      ],
      packages: [
        {
          id: 'pkg-landing-starter',
          name: 'Starter Landing Page',
          price: 1500000,
          renewalPrice: 600000,
          billingCycle: 'one-time',
          description: 'Cocok untuk jualan 1 produk unggulan',
          popular: false,
        },
        {
          id: 'pkg-landing-pro',
          name: 'Pro Sales Funnel',
          price: 2600000,
          renewalPrice: 850000,
          billingCycle: 'one-time',
          description: 'Funnel penjualan lengkap dengan thank-you page',
          popular: true,
        },
      ],
    },
    {
      id: 'prod-company',
      name: 'Website Company Profile',
      category: 'website',
      description: 'Website resmi perusahaan & bisnis untuk meningkatkan kredibilitas, branding, dan daya tarik partner bisnis.',
      badge: 'Rekomendasi',
      active: true,
      features: [
        'Hingga 5 Halaman Utama',
        'Free Domain .com / .co.id (1 Tahun)',
        'Cloud Hosting 5GB SSD CPanel',
        '3 Akun Email Bisnis Profesional',
        'CMS WordPress / Admin Dashboard',
        'SSL Security Certificate',
      ],
      packages: [
        {
          id: 'pkg-com-business',
          name: 'Business Standard',
          price: 2900000,
          renewalPrice: 950000,
          billingCycle: 'yearly',
          description: 'Solusi standar perusahaan & instansi',
          popular: false,
        },
        {
          id: 'pkg-com-corporate',
          name: 'Corporate Premium',
          price: 4900000,
          renewalPrice: 1500000,
          billingCycle: 'yearly',
          description: 'Paket premium dengan prioritas support 24/7',
          popular: true,
        },
      ],
    },
    {
      id: 'prod-ecommerce',
      name: 'Toko Online & E-Commerce',
      category: 'website',
      description: 'Platform toko online mandiri dengan hitung ongkir otomatis JNE/J&T/SiCepat dan pembayaran otomatis.',
      badge: 'Best Value',
      active: true,
      features: [
        'Katalog produk tanpa batas',
        'Integrasi kurir JNE, J&T, SiCepat',
        'Checkout WhatsApp & Payment Gateway',
        'Panel kelola stok & pesanan',
      ],
      packages: [
        {
          id: 'pkg-ecom-umkm',
          name: 'UMKM Shop Pro',
          price: 3600000,
          renewalPrice: 1200000,
          billingCycle: 'yearly',
          description: 'Toko online lengkap untuk brand lokal',
          popular: true,
        },
      ],
    },
    {
      id: 'prod-hosting',
      name: 'Managed Hosting & Domain',
      category: 'hosting',
      description: 'Layanan sewa server cloud cepat dan perpanjangan nama domain dengan dukungan teknis langsung.',
      badge: 'Infrastruktur',
      active: true,
      features: ['NVMe Storage Cepat', 'Free SSL Auto-Renew', 'Daily Automated Backup'],
      packages: [
        {
          id: 'pkg-host-nvme',
          name: 'NVMe Cloud 10GB',
          price: 650000,
          renewalPrice: 650000,
          billingCycle: 'yearly',
          description: 'Server cloud cepat khusus WordPress & Laravel',
          popular: false,
        },
      ],
    },
  ],
  services: [
    {
      id: 'srv-1',
      clientId: 'cli-1',
      clientName: 'Budi Santoso',
      productId: 'prod-ecommerce',
      packageId: 'pkg-ecom-umkm',
      productName: 'Toko Online & E-Commerce',
      packageName: 'UMKM Shop Pro',
      websiteName: 'Toko Berkah Mandiri',
      domain: 'tokoberkah.id',
      url: 'https://tokoberkah.id',
      billingCycle: 'yearly',
      price: 3600000,
      startDate: '2025-09-24',
      expiryDate: '2026-09-24',
      status: 'expiring_soon',
      autoRenewReminder: true,
      credentials: {
        cpanelUrl: 'https://cpanel.tokoberkah.id:2083',
        cpanelUser: 'berkahuser',
        cpanelPassword: 'BerkahPass#2025!',
        cmsAdminUrl: 'https://tokoberkah.id/wp-admin',
        cmsUser: 'admin_budi',
        cmsPassword: 'TokoOnlineBudi@99',
        emailProvider: 'Webmail Cpanel (Roundcube)',
        emailAddress: 'halo@tokoberkah.id',
        emailPassword: 'EmailBerkah*2025',
        serverIp: '103.145.22.88',
        nameservers: ['ns1.naufalcloud.id', 'ns2.naufalcloud.id'],
        notes: 'Toko online produk fashion & sandal kulit.',
      },
    },
    {
      id: 'srv-2',
      clientId: 'cli-2',
      clientName: 'Siti Rahmah',
      productId: 'prod-company',
      packageId: 'pkg-com-corporate',
      productName: 'Website Company Profile',
      packageName: 'Corporate Premium',
      websiteName: 'Cahaya Abadi Logistik',
      domain: 'cahayaabadilogistik.com',
      url: 'https://cahayaabadilogistik.com',
      billingCycle: 'yearly',
      price: 4900000,
      startDate: '2025-04-10',
      expiryDate: '2027-04-10',
      status: 'active',
      autoRenewReminder: true,
      credentials: {
        cmsAdminUrl: 'https://cahayaabadilogistik.com/wp-admin',
        cmsUser: 'admin_cahaya',
        cmsPassword: 'LogistikPro#2025',
        serverIp: '103.145.22.90',
        nameservers: ['ns1.naufalcloud.id', 'ns2.naufalcloud.id'],
        notes: 'Website profil perusahaan ekspedisi kargo.',
      },
    },
    {
      id: 'srv-3',
      clientId: 'cli-3',
      clientName: 'dr. Hendro Wijaya',
      productId: 'prod-company',
      packageId: 'pkg-com-business',
      productName: 'Website Company Profile',
      packageName: 'Business Standard',
      websiteName: 'Klinik Sehat Medika',
      domain: 'sehatmedika.co.id',
      url: 'https://sehatmedika.co.id',
      billingCycle: 'yearly',
      price: 2900000,
      startDate: '2025-01-20',
      expiryDate: '2026-09-05',
      status: 'expired',
      autoRenewReminder: true,
      credentials: {
        cmsAdminUrl: 'https://sehatmedika.co.id/wp-admin',
        cmsUser: 'admin_klinik',
        cmsPassword: 'SehatKlinik#2025',
        emailProvider: 'Zoho Mail Business',
        emailAddress: 'kontak@sehatmedika.co.id',
        emailPassword: 'ZohoMedika%2025',
        serverIp: '103.145.22.95',
        nameservers: ['ns1.naufalcloud.id', 'ns2.naufalcloud.id'],
        notes: 'Domain .co.id membutuhkan legalitas SIUP & KTP dokter.',
      },
    },
    {
      id: 'srv-4',
      clientId: 'cli-4',
      clientName: 'Dewi Lestari',
      productId: 'prod-landing',
      packageId: 'pkg-landing-pro',
      productName: 'Jasa Pembuatan Landing Page',
      packageName: 'Pro Sales Funnel',
      websiteName: 'Artha Interior Studio',
      domain: 'arthainterior.com',
      url: 'https://arthainterior.com',
      billingCycle: 'yearly',
      price: 1200000,
      startDate: '2025-11-05',
      expiryDate: '2026-11-05',
      status: 'active',
      autoRenewReminder: true,
      credentials: {
        cmsAdminUrl: 'https://arthainterior.com/wp-admin',
        cmsUser: 'dewi_artha',
        cmsPassword: 'ArthaDesign#2025',
        emailAddress: 'hello@arthainterior.com',
        emailPassword: 'ArthaMail*123',
        notes: 'Portfolio interior modern minimalis.',
      },
    },
  ],
  invoices: [
    {
      id: 'inv-1',
      invoiceNumber: 'INV/2026/09/001',
      clientId: 'cli-1',
      clientName: 'Budi Santoso',
      serviceId: 'srv-1',
      websiteName: 'Toko Berkah Mandiri',
      items: [
        {
          id: 'item-1',
          description: 'Perpanjangan Hosting NVMe Cloud & Domain tokoberkah.id (1 Tahun)',
          quantity: 1,
          unitPrice: 1200000,
          total: 1200000,
        },
        {
          id: 'item-2',
          description: 'Paket Maintenance & Security Protection E-Commerce Tahunan',
          quantity: 1,
          unitPrice: 2400000,
          total: 2400000,
        },
      ],
      subtotal: 3600000,
      discount: 200000,
      couponCode: 'SETIA2026',
      total: 3400000,
      issueDate: '2026-09-10',
      dueDate: '2026-09-24',
      status: 'unpaid',
      notes: 'Perpanjangan layanan website e-commerce tokoberkah.id periode 2026-2027.',
    },
    {
      id: 'inv-2',
      invoiceNumber: 'INV/2026/09/002',
      clientId: 'cli-3',
      clientName: 'dr. Hendro Wijaya',
      serviceId: 'srv-3',
      websiteName: 'Klinik Sehat Medika',
      items: [
        {
          id: 'item-3',
          description: 'Perpanjangan Domain sehatmedika.co.id + Cloud Hosting SSD 5GB (1 Tahun)',
          quantity: 1,
          unitPrice: 2900000,
          total: 2900000,
        },
      ],
      subtotal: 2900000,
      discount: 0,
      total: 2900000,
      issueDate: '2026-08-25',
      dueDate: '2026-09-05',
      status: 'overdue',
      notes: 'Tagihan sudah melewati batas jatuh tempo.',
    },
    {
      id: 'inv-3',
      invoiceNumber: 'INV/2026/09/003',
      clientId: 'cli-2',
      clientName: 'Siti Rahmah',
      serviceId: 'srv-2',
      websiteName: 'Cahaya Abadi Logistik',
      items: [
        {
          id: 'item-4',
          description: 'Maintenance Bulanan & Update Konten Logistik - September 2026',
          quantity: 1,
          unitPrice: 750000,
          total: 750000,
        },
      ],
      subtotal: 750000,
      discount: 0,
      total: 750000,
      issueDate: '2026-09-01',
      dueDate: '2026-09-07',
      paidDate: '2026-09-02',
      status: 'paid',
      paymentMethod: 'BCA Virtual Account',
      notes: 'Pembayaran otomatis diverifikasi sistem.',
    },
  ],
  orders: [
    {
      id: 'ord-1',
      orderNumber: 'ORD-2026-001',
      clientId: 'cli-1',
      clientName: 'Budi Santoso',
      productId: 'prod-ecommerce',
      productName: 'Toko Online & E-Commerce',
      packageId: 'pkg-ecom-umkm',
      packageName: 'UMKM Shop Pro',
      price: 3400000,
      websiteName: 'Toko Berkah Mandiri',
      requestedDomain: 'tokoberkah.id',
      billingCycle: 'yearly',
      status: 'pending_payment',
      createdAt: '2026-09-10 10:15',
      invoiceId: 'inv-1',
      notes: 'Perpanjangan tahunan toko online.',
    },
    {
      id: 'ord-2',
      orderNumber: 'ORD-2026-002',
      clientId: 'cli-2',
      clientName: 'Siti Rahmah',
      productId: 'prod-company',
      productName: 'Website Company Profile',
      packageId: 'pkg-com-corporate',
      packageName: 'Corporate Premium',
      price: 4900000,
      websiteName: 'PT Cahaya Abadi Logistik',
      requestedDomain: 'cahayaabadilogistik.com',
      billingCycle: 'yearly',
      status: 'active',
      createdAt: '2026-09-01 09:00',
      invoiceId: 'inv-3',
      notes: 'Pesanan website corporate selesai dikerjakan.',
    },
  ],
  transactions: [
    {
      id: 'tx-1',
      transactionNumber: 'PAY-2026-0902-881',
      invoiceId: 'inv-3',
      invoiceNumber: 'INV/2026/09/003',
      clientId: 'cli-2',
      clientName: 'Siti Rahmah',
      amount: 750000,
      paymentMethod: 'bca_va',
      channelName: 'BCA Virtual Account',
      status: 'success',
      gatewayRef: 'MID-VA-9920192837',
      createdAt: '2026-09-02 11:15',
      paidAt: '2026-09-02 11:18',
    },
  ],
  coupons: [
    {
      id: 'cp-1',
      code: 'DISKONWEB10',
      discountType: 'percentage',
      discountValue: 10,
      maxDiscount: 300000,
      validUntil: '2026-12-31',
      minSpend: 1500000,
      applicableTo: 'all',
      usageLimit: 50,
      usedCount: 14,
      isActive: true,
      description: 'Diskon 10% untuk semua layanan web & perpanjangan (Maks. Rp 300rb)',
    },
    {
      id: 'cp-2',
      code: 'SETIA2026',
      discountType: 'percentage',
      discountValue: 15,
      maxDiscount: 500000,
      validUntil: '2026-12-31',
      minSpend: 1500000,
      applicableTo: 'renewal',
      usageLimit: 30,
      usedCount: 8,
      isActive: true,
      description: 'Diskon 15% khusus perpanjangan domain & hosting tahunan',
    },
    {
      id: 'cp-3',
      code: 'HEMAT250K',
      discountType: 'fixed',
      discountValue: 250000,
      maxDiscount: 250000,
      validUntil: '2026-11-30',
      minSpend: 1500000,
      applicableTo: 'all',
      usageLimit: 40,
      usedCount: 15,
      isActive: true,
      description: 'Potongan langsung Rp 250.000 untuk pembelian atau perpanjangan',
    },
  ],
  settings: {
    freelancerName: 'NahnuHost Developer',
    brandName: 'NahnuHost Studio',
    tagline: 'Jasa Pembuatan Website Profesional & Managed Cloud Service',
    email: 'kontak@nahnuhost.com',
    phone: '6281234567890',
    address: 'Jl. Pemuda No. 42, Jakarta',
    bankAccounts: [
      {
        bank: 'Bank Central Asia (BCA)',
        accountNumber: '8820-9123-456',
        accountHolder: 'NahnuHost Studio',
      },
      {
        bank: 'Bank Mandiri',
        accountNumber: '137-00-19283-77',
        accountHolder: 'NahnuHost Studio',
      },
      {
        bank: 'Bank Rakyat Indonesia (BRI)',
        accountNumber: '0206-01-098234-50-8',
        accountHolder: 'NahnuHost Studio',
      },
    ],
    paymentGateway: {
      enabled: true,
      provider: 'midtrans',
      merchantId: 'M-WEBDEV-8092',
      clientKey: 'SB-Mid-client-8hFk019Lsk892hQ',
      serverKey: 'SB-Mid-server-x92Lk010992kllQ1',
      isSandbox: true,
      autoWebhook: true,
    },
    whatsappTemplate: `Halo Kak *{clientName}*, salam hangat dari NahnuHost Studio.

Menginfokan invoice tagihan untuk perpanjangan layanan website *{websiteName}* ({domain}) sudah terbit:
📄 No. Tagihan: *{invoiceNumber}*
💰 Total Biaya: *{totalAmount}*
📅 Jatuh Tempo: *{dueDate}*

Pelanggan dapat melakukan pengecekan detail & pembayaran instan otomatis (QRIS / Virtual Account) melalui portal klien:
👉 {portalUrl}

Terima kasih atas kerjasamanya! 🙏`,
  },
  logs: [
    {
      id: 'log-1',
      actor: 'admin',
      actorName: 'NahnuHost Developer',
      action: 'Inisialisasi Sistem',
      details: 'Sistem database dan manajemen klien siap digunakan',
      category: 'system',
      timestamp: '2026-09-12 12:00',
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      target: 'admin',
      title: 'Selamat Datang di WebDev Hub',
      message: 'Database siap digunakan. Klien dan invoice dapat dikelola secara terpusat.',
      type: 'info',
      timestamp: 'Baru saja',
      read: false,
    },
  ],
};
